language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
sudo: false
env:
  global:
    - CODECLIMATE_REPO_TOKEN=5095391006b09e374e5d9232c41a09cfa6a3bdb1f9529c2485052416f743b4fe
notifications:
  slack: codeclimate:XU4Q4aPrFuBk6n2kt8sy0DLb
